// <auto-generated />
using System;
using BackEP26.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace back_EP26.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528034934_UseFilenamesForPhotos")]
    partial class UseFilenamesForPhotos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackEP26.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Coalition")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Party")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VicePresident")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            DisplayOrder = 1,
                            Name = "Iván Cepeda Castro",
                            Party = "Movimiento Político Pacto Histórico",
                            PhotoUrl = "cepeda.jpg",
                            VicePresident = "Aída Marina Quilcué Vivas"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 2,
                            Name = "Abelardo Gabriel de la Espriella",
                            Party = "Defensores de la patria",
                            PhotoUrl = "abelardo.jpg",
                            VicePresident = "José Manuel Restrepo Abondano"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 3,
                            Name = "Sergio Fajardo Valderrama",
                            Party = "Partido Dignidad & Compromiso",
                            PhotoUrl = "fajardo.webp",
                            VicePresident = "Edna Cristina del Socorro Bonilla Seba"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 4,
                            Name = "Paloma Susana Valencia Laserna",
                            Party = "Partido Centro Democrático",
                            PhotoUrl = "paloma.jpg",
                            VicePresident = "Juan Daniel Oviedo Arango"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 5,
                            Name = "Claudia Nayibe López Hernández",
                            Party = "Con Claudia imparables",
                            PhotoUrl = "claudia.jpg",
                            VicePresident = "Leonardo Humberto Huerta Gutiérrez"
                        },
                        new
                        {
                            Id = 1,
                            DisplayOrder = 6,
                            Name = "Clara Eugenia López Obregón",
                            Party = "Partido Esperanza Democrática",
                            PhotoUrl = "clara-lopez.jpg",
                            VicePresident = "María Consuelo del Río Mantilla"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 7,
                            Name = "Óscar Mauricio Lizcano Arango",
                            Party = "Coalición F.A.M.I.L.I.A",
                            PhotoUrl = "mauricio-lizcano.jpg",
                            VicePresident = "Adriana María Ramírez Martínez"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 8,
                            Name = "Raúl Santiago Botero Jaramillo",
                            Party = "Romper el sistema",
                            PhotoUrl = "santiago-botero.jpg",
                            VicePresident = "Carlos Fernando Cuevas Romero"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 9,
                            Name = "Miguel Uribe Londoño",
                            Party = "Partido Demócrata Colombiano",
                            PhotoUrl = "miguel-uribe.jpg",
                            VicePresident = "Luisa Fernanda Villegas Araque"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 10,
                            Name = "Sondra Macollins Garvin Pinto",
                            Party = "Sondra Macollins, la abogada de hierro",
                            PhotoUrl = "sandra-macollins.jpg",
                            VicePresident = "Leonardo Karam Helo"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Name = "Roy Leonardo Barreras Montealegre",
                            Party = "Partido político La Fuerza",
                            PhotoUrl = "roy-barreras.jpg",
                            VicePresident = "Martha Lucía Zamora Ávila"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            Name = "Gustavo Matamoros Camacho",
                            Party = "Partido Ecologista Colombiano",
                            PhotoUrl = "gustavo-matamoros.jpg",
                            VicePresident = "Robinson Alonso Giraldo Mira"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            Name = "Luis Gilberto Murillo Urrutia",
                            Party = "Luis Gilberto soy yo",
                            PhotoUrl = "gilberto-murillo.avif",
                            VicePresident = "Luz María Zapata Zapata"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 14,
                            Name = "Carlos Eduardo Caicedo Omar",
                            Party = "Caicedo",
                            PhotoUrl = "carlos-caicedo.jpg",
                            VicePresident = "Nelson Javier Alarcón Suárez"
                        });
                });

            modelBuilder.Entity("BackEP26.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleSubHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHonorary")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("GoogleSubHash")
                        .IsUnique();

                    b.HasIndex("IpAddress", "VotedAt");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("BackEP26.Models.Vote", b =>
                {
                    b.HasOne("BackEP26.Models.Candidate", "Candidate")
                        .WithMany("Votes")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("BackEP26.Models.Candidate", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
